apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapplication
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: python-webapplication
        image: surendharmuruganandam/pythonwebapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

